### ISSUE TITLE
Add access control code

### ISSUE THREAD

**Issue by pablo-de-andres** [materials-marketplace/python-sdk#21]
To limit which requests are allowed to an app's endpoints, a decorator (for Flask) and an Auth class (for FastAPI) have been developed. These will check the existence of a token and its validity against the platform's keycloak.

It would make sense to add this code to this SDK, in order to help app developers (potentially in a "access_control" package).

**Comment by csadorf** [comment]
Can you link to the corresponding code?

**Comment by pablo-de-andres** [comment]
I actually don't think this would fit here, but rather in the get started app, so the endpoints of the app the user creates are protected by default.
I'm closing this issue, and will bring it up again when we revise the get started app.
