### ISSUE TITLE
api_version key error

### ISSUE THREAD

**Issue by unkcpz** [materials-marketplace/python-sdk#30]
I try to update HPC app with using latest `get_app` from python-sdk but failed with the exception:

```
File ~/miniconda3/envs/hpc-app/lib/python3.9/site-packages/marketplace/app/__init__.py:41, in get_app(app_id, marketplace_host_url, access_token, **kwargs)
     39 app_service_path = f"application-service/applications/{app_id}"
     40 app_info = client.get(path=app_service_path).json()
---> 41 app_api_version = parse(app_info["api_version"])
     43 capabilities = []
     44 for capability in app_info["capabilities"]:

KeyError: 'api_version'
```

Is this already a feature on production server? or do I need to update registry of my app?

**Comment by pablo-de-andres** [comment]
This is for now only on staging, and I believe only for newly registered apps

**Comment by csadorf** [comment]
> This is for now only on staging, and I believe only for newly registered apps

So this is not fixed by #29 ?

Should we provide a default value here and also make it possible for SDK users to override this?

**Comment by pablo-de-andres** [comment]
I mean that in the current production, there is no concept of API versioning for apps, since it is from before the standard app API was created.

So apps registered back then won't have that field (or the default). 

I think it would actually be worth re-registering those apps, considering all the new changes, but we can discuss it.

**Comment by csadorf** [comment]
> So apps registered back then won't have that field (or the default).

Exactly, so they should simply default to `0.0.1`.

**Comment by pablo-de-andres** [comment]
Indeed. I made the corresponding issue on [GitLab (private)](https://gitlab.cc-asp.fraunhofer.de/MarketPlace/platform/issue-reporting/-/issues/128).

**Comment by csadorf** [comment]
> Indeed. I made the corresponding issue on [GitLab (private)](https://gitlab.cc-asp.fraunhofer.de/MarketPlace/platform/issue-reporting/-/issues/128).

We can also implement the default fallback here as an additional defensive measure.

**Comment by singhpranjali** [comment]
> > Indeed. I made the corresponding issue on [GitLab (private)](https://gitlab.cc-asp.fraunhofer.de/MarketPlace/platform/issue-reporting/-/issues/128).
> 
> We can also implement the default fallback here as an additional defensive measure.

Yes, I agree. I will add the default behavior in the sdk as well.
