### ISSUE TITLE
200 return status is not only valid status.

### ISSUE THREAD

**Issue by unkcpz** [materials-marketplace/python-sdk#9]
https://github.com/materials-marketplace/python-sdk/blob/9ec3a21fe13f5857b606afb32e0701bfa7603313/marketplace/core.py#L53

If I return others < 300 respond status, the runtime error will be raised. Which is not expected. I think we can set condition to `< 400`

**Comment by singhpranjali** [comment]
We are no longer doing error handling in the marketplace client. Closing because outdated.
